import "./globals.css";
import { Bodoni_Moda, Familjen_Grotesk, Spline_Sans_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ErrorBoundary from "@/components/ErrorBoundary";
import ServiceWorkerRegistrar from "@/components/ServiceWorkerRegistrar";
// ViewTransition ships in the React canary Next vendors for App Router
// bundles (verified: next/dist/compiled/react exports it). Server components
// compile against that copy — the `any` cast is only for the build's
// type-checker, whose stable @types/react doesn't know the export yet.
import * as React from "react";
const ViewTransition = /** @type {any} */ (React).ViewTransition;

// Bone & Ember type system — two families and an instrument.
// Display: Bodoni Moda, corrected cut. The face is ALWAYS set with
// font-optical-sizing none + 'opsz' 11 + kern normal + +0.004em tracking
// (the DISPLAY object in lib/tokens.js) — never the free optical axis,
// which is what dropped the t's hairlines below a pixel. 400 default,
// 500 ceremony-only. Roman only — no italic cut ships (italic-serif mood
// fragments are on the never-list).
const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal"],
  display: "swap",
  variable: "--font-bodoni",
  preload: true,
});

// Text: Familjen Grotesk — every word of interface. Sentence case, never
// all-caps.
const familjen = Familjen_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
  variable: "--font-familjen",
  preload: true,
});

// Measured: Spline Sans Mono — measured values only. If it isn't a
// number, it isn't mono.
const spline = Spline_Sans_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap",
  variable: "--font-spline",
  preload: true,
});

export const metadata = {
  // metadataBase makes every relative OG/twitter asset URL absolute — share
  // scrapers require absolute URLs. The OG image itself is generated by
  // app/opengraph-image.jsx (Next wires og:image + twitter:image to it
  // automatically), so no binary asset ships in the repo.
  metadataBase: new URL("https://heatwayve.app"),
  title: {
    default: "Heatwayve — Train with intention",
    template: "%s | Heatwayve",
  },
  description:
    "Unveil the best you. Evidence-based strength training — volume audits against MEV/MAV/MRV, focus-aware rotation, and progression that stays honest.",
  // Explicit canonical for "/" — the library routes already set theirs, and
  // the homepage is reachable as both apex and www.
  alternates: { canonical: "https://heatwayve.app/" },
  manifest: "/manifest.json",
  openGraph: {
    title: "Heatwayve — Train with intention",
    description:
      "Unveil the best you. Performance Lab, focus-aware rotation, progression that stays honest — cast your frame, move with intent.",
    siteName: "Heatwayve",
    locale: "en_GB",
    type: "website",
    url: "/",
  },
  twitter: {
    card: "summary_large_image",
    title: "Heatwayve — Train with intention",
    description:
      "Unveil the best you. Volume audits, smart rotation, honest progression.",
  },
  appleWebApp: {
    capable: true,
    // WAS black-translucent, for the immersive "blend": it used to be the only
    // value that made the status bar transparent so the page drew underneath.
    //
    // iOS 26.1 stopped honouring it. Installed web apps no longer get
    // transparency behind the status bar, and iOS paints its own treatment
    // over that zone regardless — the same 26.1 change that put a tint under
    // transparent tab bars natively, where Apple's advice was to stop
    // configuring transparency by hand and take the default.
    //
    // Declaring it anyway bought us the WORST of both: the system's bar over
    // our ground, AND a layout still positioned as though it owned that space
    // (viewport-fit: cover + an inset-top padding). The two treatments stacked
    // and washed out the top of every screen — reported on the session card's
    // progress rule and Quit row, and correctly noticed as "earlier versions
    // of the rebrand didn't do this": our code never changed, the OS did.
    //
    // So: take the default and let the system own the status bar. Our top
    // padding goes back to being ours rather than compensation for a zone we
    // no longer control. The alternative doing the rounds — a fixed div with
    // backdrop-filter — only re-creates the effect iOS removed, cannot
    // restore real transparency, and is on the design system's never-list.
    //
    // NOTE: iOS reads this ONLY at install time. Remove and re-add the Home
    // Screen app to see any change here.
    statusBarStyle: "default",
    title: "Heatwayve",
  },
  icons: {
    apple: "/apple-touch-icon.png",
    // Tab favicons are their own cut: browsers render favicons square, so
    // the mark's plate radius (18.75%) is baked into the alpha. The glass
    // set stays full-bleed for surfaces that mask for us (iOS, Android
    // maskable). Fresh filenames double as a favicon-cache bust.
    icon: [
      {
        url: "/heatwayve/heatwayve-tab-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/heatwayve/heatwayve-tab-512.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
  },
};

export const viewport = {
  // themeColor: kept for non-Safari browsers + PWA chrome that still read it.
  // IMPORTANT (Safari 26): Safari STOPPED honouring theme-color for the
  // toolbar tint. It now samples the background-color of a fixed/sticky edge
  // element, falling back to <body>, at FIRST PAINT (JS bg changes don't
  // update it). Our chrome reads correctly because html/body carry
  // var(--ground) in globals.css — that ground tone IS what tints the
  // toolbar. DO NOT remove the html/body background thinking themeColor
  // covers it. (This exact trap already caused a regression once.)
  // Bone & Ember: a media pair so browsers that DO honour theme-color
  // follow the mode contract.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F2E9E3" },
    { media: "(prefers-color-scheme: dark)", color: "#1A1512" },
  ],
  // colorScheme via the viewport API rather than a manual <meta> in <head>
  // — Next dedupes/manages it and warns on hand-written viewport meta.
  // `light dark`: the mode contract. Controls UA form controls, scrollbars,
  // and the default canvas colour per system appearance.
  colorScheme: "light dark",
  width: "device-width",
  initialScale: 1,
  // NO maximumScale / userScalable lock. It arrived with this file's first
  // commit as PWA boilerplate and never earned a reason of its own, while it
  // cost pinch-zoom to anyone who magnifies to read (Lighthouse flags it).
  // iOS has ignored the lock for user-initiated zoom since iOS 10, so it only
  // ever bound Android.
  //
  // The one thing it plausibly still bought was suppressing iOS's
  // zoom-on-focus, which fires on focusable inputs under 16px. That is now
  // fixed at the cause instead: every focusable input in the app is >= 16px
  // (BugReportSheet's textarea was the last one at 14px). Keep new inputs at
  // 16px or larger and the lock stays unnecessary.
  //
  // viewport-fit: cover STAYS, even though the immersive status-bar look it
  // was originally chosen for is gone (iOS 26.1 — see appleWebApp above).
  // The load-bearing reason was always the second one: without cover, every
  // env(safe-area-inset-*) in the app resolves to 0, and the bottom sheets
  // and toasts genuinely need the home-indicator inset. Removing it to
  // "match" the new status-bar handling would silently break the chin.
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bodoni.variable} ${familjen.variable} ${spline.variable}`}
      // Parse-time colour scheme on <html> so the right canvas exists
      // before globals.css (an external stylesheet) loads. The gap between
      // first paint and stylesheet application is when the browser paints
      // the UA-default canvas — the load-flash / iOS standalone swipe-back
      // "shimmer". color-scheme here makes the UA canvas follow the system
      // appearance; the inline <style> in <head> below pins the actual
      // ground tone per mode (an inline style attribute can't express a
      // media query, so the background lives in that tag instead — same
      // parse-time guarantee).
      style={{ colorScheme: "light dark" }}
    >
      <head>
        {/* Appearance override, applied at PARSE time. The Profile toggle
            (lib/theme.js) stores a PER-PROFILE preference; profile
            resolution is itself just a localStorage read (forge:active),
            so the active profile's mode lands before first paint. Without
            this blocking script every launch would paint the system mode
            and then snap — the same flash class the inline background
            below exists to prevent. Auto stores nothing, so the default
            path does no work. Must stay in sync with lib/theme.js. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              'try{var d=document.documentElement,p=JSON.parse(localStorage.getItem("forge:active")||"null"),t=p?JSON.parse(localStorage.getItem("forge:"+p+":theme")||"null"):null;if(t==="light"||t==="dark"){d.style.colorScheme=t}d.dataset.mode=(t==="light"||t==="dark")?t:(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light")}catch(e){}',
          }}
        />
        {/* Parse-time ground tone — see the <html> style note. One rule:
            light-dark() re-resolves against whatever color-scheme the
            script above just set, so the manual override wins the same
            parse-time race for free. Must stay in sync with --ground in
            globals.css. */}
        <style
          dangerouslySetInnerHTML={{
            __html: "html{background:light-dark(#F2E9E3,#1A1512)}",
          }}
        />
        {/* Build-output-verified manual tags. Next 16's Metadata API
            emits apple-mobile-web-app-status-bar-style (from
            appleWebApp.statusBarStyle), apple-mobile-web-app-title
            (from appleWebApp.title), apple-touch-icon (from icons.apple),
            and the cross-platform mobile-web-app-capable automatically
            — all four were duplicated previously and the duplicates were
            silently disabling viewport-fit cover + black-translucent on
            iOS Safari (chin + letterbox + opaque status bar).

            What Next does NOT emit, and what iOS still requires for
            splash screens + full standalone PWA behaviour, is
            apple-mobile-web-app-capable (the Apple-prefixed legacy tag —
            deprecated but still required by iOS Safari per
            https://github.com/vercel/next.js/issues/74524). That's the
            single tag that stays here. */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* Structured data: SoftwareApplication — discoverability signal for
            app-like tools. Static, so a plain server-rendered script tag. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              name: "Heatwayve",
              applicationCategory: "HealthApplication",
              operatingSystem: "Web, iOS, Android (PWA)",
              offers: { "@type": "Offer", price: "0", priceCurrency: "GBP" },
              description:
                "Unveil the best you. Evidence-based strength training with live volume auditing and focus-aware exercise rotation.",
              url: "https://heatwayve.app",
            }),
          }}
        />
      </head>
      <body>
        <ServiceWorkerRegistrar />
        <ErrorBoundary>
          {/* <main> because this wrapper IS the document's dominant content:
              every route renders through it and the layout has no nav or
              footer landmark outside it. Routes must NOT render their own
              <main> — it would nest, and a document gets one.

              .forge-page (globals.css): document-height wrapper that paints
              the ground substrate (bone/ash + the baked-in paper texture)
              across the FULL scrollable document. Texture lives in the
              ground's own background — substrate, never overlay — so it
              composites once and never sits over type or data marks.
              Deliberately no fixed layers at the viewport edges: Safari 26
              paints opaque colour-extension slabs behind its chrome
              whenever a fixed/sticky element borders a viewport edge
              (WebKit bug 301756), which suppresses the translucent
              scroll-under treatment at both the status bar and URL bar. */}
          <main className="forge-page">
            {/* The ONE transition boundary: route navigations and in-shell
                screen swaps both update this subtree inside a React
                transition, so both animate through the same class-mapped
                slide vocabulary (globals.css ::view-transition-*(.forge-vt-*)).
                Typed "nav-back" transitions (lib/nav-transitions.js) slide
                down; everything else slides up. The substrate is outside
                the boundary, so it is never double-captured. */}
            <ViewTransition
              default={{
                "nav-back": "forge-vt-back",
                default: "forge-vt-forward",
              }}
            >
              {children}
            </ViewTransition>
          </main>
        </ErrorBoundary>
        {/* Status-bar handling: iOS owns the bar (statusBarStyle: default,
            since 26.1 stopped honouring black-translucent). viewport-fit:
            cover STAYS — it is what makes every env(safe-area-inset-*)
            resolve at all, and the bottom sheets rely on the home-indicator
            inset. The standalone env(safe-area-inset-top) padding on
            .forge-page keeps content clear of whatever the system reserves. */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
